# Generated by Django 6.0.2 on 2026-02-14 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralizedLaborFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.TextField()),
                ('publish_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaborFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.TextField()),
                ('generalized_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualificationApp.generalizedlaborfunction')),
            ],
        ),
        migrations.CreateModel(
            name='LaborFunctionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KNOW', 'Знание'), ('SKILL', 'Умение'), ('ACT', 'Трудовое действие')], max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('name', models.TextField()),
                ('labor_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='QualificationApp.laborfunction')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualificationApp.employee')),
                ('skill_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualificationApp.laborfunctiondetails')),
            ],
            options={
                'unique_together': {('employee', 'skill_detail')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(related_name='employees', through='QualificationApp.EmployeeSkillProgress', to='QualificationApp.laborfunctiondetails'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('generalized_functions', models.ManyToManyField(related_name='posts', to='QualificationApp.generalizedlaborfunction')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QualificationApp.post'),
        ),
        migrations.AddField(
            model_name='generalizedlaborfunction',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualificationApp.profession'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QualificationApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_reached', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualificationApp.employee')),
                ('skill_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualificationApp.laborfunctiondetails')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QualificationApp.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QualificationApp.project')),
                ('required_skills', models.ManyToManyField(related_name='tasks', to='QualificationApp.laborfunctiondetails')),
            ],
        ),
    ]
