# Generated by Django 6.0.2 on 2026-02-18 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualificationApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeeskillprogress',
            options={'verbose_name': 'Прогресс навыка', 'verbose_name_plural': 'Прогресс навыков'},
        ),
        migrations.AlterModelOptions(
            name='generalizedlaborfunction',
            options={'verbose_name': 'ОТФ', 'verbose_name_plural': 'Обобщенные трудовые функции'},
        ),
        migrations.AlterModelOptions(
            name='laborfunction',
            options={'verbose_name': 'Трудовая функция', 'verbose_name_plural': 'Трудовые функции'},
        ),
        migrations.AlterModelOptions(
            name='laborfunctiondetails',
            options={'verbose_name': 'Деталь функции', 'verbose_name_plural': 'Знания, умения, действия'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='skilllog',
            options={'verbose_name': 'Лог навыка', 'verbose_name_plural': 'История изменений навыков'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Нужно сделать'), ('in_progress', 'В работе'), ('completed', 'Завершена')], default='todo', max_length=20),
        ),
    ]
