# Generated by Django 6.0.2 on 2026-02-25 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualificationApp', '0002_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код ОКПДТР'),
        ),
        migrations.AddField(
            model_name='post',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QualificationApp.profession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='generalized_functions',
            field=models.ManyToManyField(blank=True, to='QualificationApp.generalizedlaborfunction', verbose_name='Связанные ОТФ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(),
        ),
    ]
