# Generated by Django 6.0.2 on 2026-02-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QualificationApp', '0003_post_code_post_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profession',
        ),
    ]
