# Generated by Django 6.0.2 on 2026-02-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualificationApp', '0004_remove_post_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(max_length=500, verbose_name='Путь к папке с XML')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Настройки парсера',
                'verbose_name_plural': 'Настройки парсера',
            },
        ),
    ]
