# Generated by Django 6.0.2 on 2026-03-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualificationApp', '0005_parsersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='external_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
