# Generated by Django 6.0.2 on 2026-03-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualificationApp', '0006_employee_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Нужно сделать'), ('in_progress', 'В работе'), ('to_confirm', 'Нужно подтвердить'), ('completed', 'Завершена')], default='todo', max_length=20),
        ),
    ]
