# Generated by Django 6.0.2 on 2026-03-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QualificationApp', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='grade',
            field=models.CharField(blank=True, choices=[('excellent', 'Отлично'), ('good', 'Хорошо'), ('rework', 'На переделку')], max_length=20, null=True, verbose_name='Оценка руководителя'),
        ),
    ]
